pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["sleep"]
    args: ["99d"]
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
  - name: git-tool
    image: alpine/git:latest
    command: ["sleep"]
    args: ["99d"]
  volumes:
  - name: docker-config
    projected:
      sources:
      - secret:
          name: regcred
          items:
            - key: .dockerconfigjson
              path: config.json
"""
        }
    }

    environment {
        ECR_URL = "564415061836.dkr.ecr.us-west-2.amazonaws.com/django-app-repo"
        IMAGE_TAG = "v${BUILD_NUMBER}"
        GIT_REPO_URL = "github.com/ihorborys/DevOps.git"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build & Push to ECR (Kaniko)') {
            steps {
                container('kaniko') {
                    sh """
                        /kaniko/executor \
                        --context ${env.WORKSPACE} \
                        --dockerfile ${env.WORKSPACE}/Django/Dockerfile \
                        --destination ${ECR_URL}:${IMAGE_TAG} \
                        --cache=true
                    """
                }
            }
        }

        stage('Update Helm Tag in Git') {
            steps {
                container('git-tool') {
                    withCredentials([usernamePassword(credentialsId: 'github-token', passwordVariable: 'GIT_PASS', usernameVariable: 'GIT_USER')]) {
                        sh """
                            git config --global --add safe.directory '*'
                            git config user.email "jenkins@rapidfire.com"
                            git config user.name "Jenkins CI"

                            # Оновлюємо таг у values.yaml
                            sed -i 's/tag: .*/tag: "${IMAGE_TAG}"/' charts/django-app/values.yaml

                            git add charts/django-app/values.yaml
                            git commit -m "Bump image version to ${IMAGE_TAG} [skip ci]"
                            git push https://${GIT_USER}:${GIT_PASS}@${GIT_REPO_URL} HEAD:final-project
                        """
                    }
                }
            }
        }
    }
}