# Кількість реплік для Django
replicaCount: 1

image:
  # Тимчасово ставимо nginx для успішного скріншоту
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "v7"

service:
  type: LoadBalancer
  port: 80

# Налаштування автоскейлінгу (згідно з ДЗ: 2-6 реплік)
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

# Загальні налаштування (ConfigMap)
configData:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "django_user"

# Секція для PostgreSQL
postgresql:
  image:
    repository: postgres
    tag: "v7"
  dbName: "django_db"
  user: "django_user"
  password: "pass9764gd"
  storageSize: 1Gi