postgresql:
  enabled: true
  # ФОРСУЄМО надійний шлях до образу
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 15.3.0
    pullPolicy: IfNotPresent
  auth:
    database: "django_db"
    username: "django_user"
    password: "pass9764gd"
  primary:
    persistence:
      enabled: false  # Залишаємо вимкненим, щоб не чекати на диски