apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "django_db"
            - name: POSTGRES_USER
              value: "django_user"
            - name: POSTGRES_PASSWORD
              value: "pass9764gd"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db # ЦЕ ВАЖЛИВО: Django буде шукати базу за цим ім'ям
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432