apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-app.fullname" . }}-db-secret
type: Opaque
data:
  # Пароль має бути в base64.
  # Для ДЗ ми можемо взяти його з values, але в реальному житті він би генерувався або брався з Vault
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}